tealeg/xlsx

cell.go
cell_test.go
file.go
file_test.go
lib.go
row.go
sheet.go
sheet_test.go
xmlStyle.go
xmlStyle_test.go

xlsx module has tree structure like this:
```
File -> Sheet -> Row -> Cell
Cell -> Style
```
And each child had reference to parent too, but Sheet -> File and Cell -> Row links didn't use pointer. Sheet and Cell structs had parents as instance. I think it is a bug (e.g. sheet1's parent and sheet2's parent are different instance). And each Cell object had Style instance. Now Cell type has Style pointer and cells share style instance. 
I made sample spreadsheet (it contains 1600 cells * 4 sheets) with following fix reduce memory usage 51% (3.22 MB -> 1.57MB). Performance improves 1.7%.
```go
// sample benchmark code
package main
import (
"log"
"time"
"runtime"
"github.com/tealeg/xlsx"
)
func main() {
var book *xlsx.File
start := time.Now()
for i := 0; i < 100; i++ {
book, _ = …
```

reduce memory usage

---

README.org

`error` is a type keyword in Go. Could you change it to `err`? And thanks for the package!

error -> err

---

write.go
write_test.go

I needed this for a project of mine so I figured it'd be useful. It allows the writing of any struct (e.g. `type Person struct{}`) to a row, cell-by-cell.
This library doesn't have support for writing `int64` to a cell, so on a 32-bit platform it may overflow an `int64` member. I could submit a PR that adds a `SetInt64` function or just change `SetInt` to `int64`

Added functionality for writing a struct to a row

---

cell_test.go
sheet.go
style.go
style_test.go
xmlStyle.go

I noticed that number formats weren't being unmarshalled correctly from the excel files I was using, and traced it back to the fact it's attributes weren't marked as attributes. Since Marshal is handwritten it was only affecting unmarshalling. Fixing this exposed some other issues in number format handling that was causing the tests to fail:
1. The number formats were kept in a global map, even though their ids
are reused between different workbooks. This caused the tests to
interfere with each other. I fixed this by making it a per-stylesheet
which matches Excel's model.
2. The method makeXLSXStyleElements returns a nil initialized numFmt.
Its id was 0 which conflicts with the builtin general number format.
It was only used in 1 place (and it no-oped before because of the
previous bug) …

Fix a number of small issues with number format handling

---

xmlStyle.go

Most of these I sourced from this list:
http://polymathprogrammer.com/2011/02/15/built-in-styles-for-excel-open-xml/
I found 41 through 44 in ECMA-376 Fourth Edition, Part 1, in
/OpenOfficeXML-SpreadsheetMLStyles/presetCellStyles.xml
(linked here:
https://www.dropbox.com/s/smvb305g6rfb6xj/presetCellStyles.xml)

Add support for the builtin number formats

---

xmlStyle.go

The map wasn't created until the first addFmt was called, which
isn't called for custom formats, which was preventing builtin
formats from being read.

Fix number formats in workbooks where no custom formats are created

---

file.go
file_test.go

Uses a string replacement to bypass current limitation on
encoding/xml.
Proposed for @tealeg to approve or veto.

Hack to fix #63 and #91.

---

cell.go
cell_test.go

Updates `Cell.Bool()` to more accurately return a boolean value based on the cell's type.
If it's a boolean cell type, return the boolean value.
If it's a numeric type, `False` for zero and `True` for anything else.
Otherwise, return `False` for `""` or `True` for anything else.

Improve boolean check.

---

lib.go
lib_test.go

This fixes the problem and tests all still pass. But is it
the correct solution? Can we get rid of the recover() function?
Fixes #114.

Fix for a nil formula when the raw cell type is error (e).

---

cell.go
cell_test.go

Should hopefully fix any time format thrown at it.
This is the first step in making `FormattedValue` more dynamic.

Make date parsing dynamic.

---

cell.go
cell_test.go
xmlStyle.go
xmlStyle_test.go

fix adding duplicate NumFmt; 
fix the builtin number format code such as 00+E00 which was not recognized as builtin NumFormt. Microsoft Excel will warn the broken file when add builtin format code as a user defined NumFmt.
ea2b7067d5dde4c330450404001a103591440302 will output the float number according the number of the leading zero. e.g. the float less than 0.0001, such as 0.000005 will output as 5e-06, while 103.22 will output as origin.

fix adding duplicate NumFmt

---

lib.go
lib_test.go

There is a bug with hidden cells introduced in this commit.
https://github.com/tealeg/xlsx/commit/00de551dc6de154cfa6db6b102a41448b251b8ad#diff-1861a0c40780efdec0f4e6e2e19b3d44R429
```diff
-			row.Cells[cellX].date1904 = file.Date1904
-			row.Cells[cellX].Hidden = rawrow.Hidden || (len(cols) > cellX && cols[cellX].Hidden)
+			cell.date1904 = file.Date1904
+			cell.Hidden = rawrow.Hidden || (len(cols) > cellX && cell.Hidden)
```
`cell` is set to `row.Cells[cellX]` so replacing `cols[cellX].Hidden` with `cell.Hidden` is incorrect. I changed it back to `cols[cellX].Hidden` so that the column hidden status is properly checked. I also added a test case for this.

properly check column hidden for cell hidden logic

---

lib.go

Comment referred to the method as "String()" instead of "Error" and referred to the "`os.Error` interface" instead of the `builtin.error` interface. `os.Error` hasn't been around since before Go 1, AFAIK.

Fix doc comment for XLSXReaderError.Error()

---

lib.go
lib_test.go

The value of the "r" attribute of a <row> was being used as part of a test
in a loop which loaded default values into a row. However, the value in
the attribute could be higher than the number of rows, causing a panic
due to an index error.
fixes #125

Fix panic on invalid value for "r" attribute in <row>.

---

fuzzy_test.go

The library is given a slightly modified version of testfile.xlsx and tested for uncaught panics.
There are a few problems with the test, but I see no way around them:
The library panics in a goroutine and terminates the test, without the test every printing logged output, thus printing information to stdout as the test proceeds is the only way of getting output. I suppressed output unless the `-test.v` flag is set. The test always prints the random seed (the only line alway printed) that is is using in order for the test to be repeatable should it fail(set using `-test.seed`).
Thus when running the test the seed will be output, if it it fails the test can be rerun with the `-test.v` and `-test.seed=<seed>` flags to see what modification to the file broke the library. 
The test currently …

Adds a test the randomly modifies parts of working xlsx documents

---

sheet.go
xmlWorksheet.go

In Microsoft Excel for Mac 2011 width setting were not applied to columns. The attribute `customWidth` has to be set to `1` when a user has changed it ([DocumentFormat.OpenXml.Spreadsheet.Column](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.column(v=office.14).aspx)). This has been remedied in this patch and the `customWidth` attribute is only applied when a user has explicitly changed the width of a column.
Previously default width was automatically applied during `maybeAddCol`, I removed it from here since it gets applied anyway in `makeXLSXSheet`. That way the we can check if `customWidth` need to be applied or not.
I also enabled modifications to `DefaultColWidth` and `DefaultRowHeight`. Now DefaultColWidth can be used instead of modifying each column …

Apply customWidth attribute to cols and enable changing defaults

---

lib.go

Should be self-explanatory. Otherwise doing things like `row.AddCell()` on a file you just read can panic on a nil pointer dereference.

Set Sheet attr of each Row in readSheetFromFile

---

sheet.go

As mentioned in #158, applyNumberFormat was always 0 in the output.
For some reason, Excel didn't care, but all the other clients I tried (Google docs, OpenOffice, Gnumeric) did care.
Fixes #158.

Set ApplyNumberFormat in handleNumFmtIdForXLSX

---

cell.go
cell_test.go
lib.go
sheet.go
sheet_test.go

…for instance.
This is a very straight forward PR, nothing fancy. I found myself wanting to format my cells many different ways (various currencies, percentage etc..). I know that in most cases I could have used `SetFloatWithFormat` but I needed to apply the format to the result of a formula. I could have added a `SetFormulaWithFormat` but even with that, I think that it makes a lot of sense to export the format field. After all, this is something Excel users can access directly and there are a lot of edge cases where it might be needed.

export the cell numeric format so a formula cell can be set to percent

---

lib.go
lib_test.go

This fixes an issue where a row would be accidentally overwritten with a blank row, if the following (blank) row was omitted in the worksheet file.
[Here is a file](https://s3-eu-west-1.amazonaws.com/boxofrad/Shared/bug.xlsx) (exported from Google Sheets) that exposes the problem - It's not possible to access the cell at reference: **A4**.
I'm not sure what the original reason for subtracting the `minRow` was, but it seems erroneous to me.
Thanks! :sparkling_heart:

Fix "off by one" bug when the spreadsheet omits empty rows

---

write.go
write_test.go

Now WriteSlice can write slice with the type []interface{}, for example:
```go
s := []interface{}{"test", 1, true}
row.WriteSlice(&s,-1)
```

WriteSlice supports writing []interface{}

---

style.go

The code is implemented, however, it is not actually causing the cell to wrap. This may only be part of the solution. If there is more or if wraptext is not possible then this PR can be dropped.

added WrapText to alignment

---

lib.go
lib_test.go

There's an issue when "shared" formulas have absolute cell references.  This fix will take that into consideration when shifting cells.
Please review @tealeg

Fix shared formulas with absolute cell references ($)

---

lib.go
lib_test.go

Will skip string literals in a formula, so we don't unintentionally shift those looking like cell labels.
For example, ```IF(C23>=E$12,"Q4",IF(C23>=$D$12,"Q3",IF(C23>=C$12,"Q2","Q1")))```, "Q4", "Q3", "Q2", and "Q1" should not be shifted.
Please review @tealeg  
Thanks!

Skip string literals when trying to shift cells in shared formula

---

cell.go
cell_test.go
compatibility_test.go
file.go
file_test.go
lib_test.go
write_test.go

As discussed in the comments in #191, fixes FormattedValue to return `(string, error)` instead of just `string`.
Previously, if there was an error, the `error.Error()` was just returned as the string value. This worked, but resulted in error-free execution with the potential for bad output.
See 9e8fb11ea051b80749b9a18fdcbc97ebca291b87 for the actual, very minor, change.
Then commit c88ad73d9b7d4d9c8c60b4726a67d5a6e602cf4d for the test changes that had to be done.

Fix for 191 formatted value return error.

---

cell.go
cell_test.go
lib.go

file.DefinedNames would be an array of the proper size, but all values would be the last &entry, as they were all referencing the same memory location. 
e.g. 
**Memory addresses and values before fix (file with three defined names):**
[0xc8201363c0 0xc8201363c0 0xc8201363c0]
&{Sheet1!$E$5:$G$7 NamedRange3       0 0 false false false false false false}
&{Sheet1!$E$5:$G$7 NamedRange3       0 0 false false false false false false}
&{Sheet1!$E$5:$G$7 NamedRange3       0 0 false false false false false false}
**Memory addresses and values after fix:**
[0xc820136280 0xc820136318 0xc8201363b0]
&{Sheet1!$A$1:$C$2 NamedRange1       0 0 false false false false false false}
&{Sheet1!$E$1:$G$2 NamedRange2       0 0 false false false false false false}
&{Sheet1!$E$5:$G$7 NamedRange3       0 0 false …

Fixed DefinedNames.DefinedName pointer issue.

---

col.go
lib.go
row.go
sheet.go
sheet_test.go
xmlWorksheet.go

This patch adds basic support for groups. Nothing fancy, you have to manually set the row/column levels. The only automatic thing right now is maximum level determining in the `makeXLSXSheet` method.

Add basic grouping support

---

write.go
write_test.go

@tealeg I think this would be a right fix to #237 #238 
the panic is caused by calling Elem on non Ptr kind value,
this fix makes sure the value is a Ptr before calling Elem

fix pointer to slice check panic on WriteSlice

---

cell.go
cell_test.go
date.go
date_test.go

@tealeg @frezadev
incorrect parsed date fix #229 #241 
the original version has problems when calculating seconds value & has rounding issues
this fix would calculation the seconds value correctly and round the it nearest 1us.

Incorrect parsed date fix

---

xmlWorksheet.go
xmlWorksheet_test.go

When doing prefix checking in getExtent for merged cells, need to stick `:` to the reference,
otherwise getExtent can return wrong info for a non merged cell A1 if there is a merged cell at A1n.
this would possibly close these two issues: https://github.com/tealeg/xlsx/issues/230 https://github.com/tealeg/xlsx/issues/212

Fix prefix check for getExtent for merged cells

---

cell.go
cell_test.go
write.go
write_test.go

The commit make WriteSlice and WriteStruct write value with builtin format to general format, and make them support time.Time.
Add more types to SetValue and add test for cell.SetValue
Besides, I think Cell.SetInt, cell.SetInt64, cell.SetFloat should also use SetValue for setting values, so that the cell has a general format which can be recognized properly by spreadsheet program. I didn't do it in the commit because I'm not unsure if the change will affect other parts. It's my pleasure for doing that if you are sure it.

make WriteSlice and WriteStruct write some value using SetValue

---

lib.go
lib_test.go

This is the fix for the panic when a shared formula contains a defined name.  For example, SUM(D44:H44)*IM_A_DEFINED_NAME
Please review @tealeg Thanks!

Panic: runtime error: slice bounds out of range

---

.gitignore
.travis.yml
README.org

Changes:
- .travis.yml:
- bump go versions to 1.5 & 1.6
- add `go vet`
- add go test coverage
- README.org:
-  add badges for travis, code coverage (codecov) and license
- .gitignore:
- add "coverage.txt"
In order to use Codecov, you need to sign up first. It is straight forward: just [sign up with GitHub](https://codecov.io/login/github) and then add the repository that you wish to monitor. The service, like Travis, is free for open source projects. The biggest benefit of codecov is that it supports branch coverage whereas Coveralls does not. Codecov also has a [browser plugin](https://codecov.io/#features) that overlays code coverage on diffs and files.

Add support for code coverage (codecov.io) and update Travis

---

cell.go
file.go
file_test.go
lib.go
style.go
xmlStyle.go

@tealeg: Love this library. 
I was using it again at work and noticed a fair amount of the code doesn't necessarily adhere to [typical Go conventions](https://github.com/golang/go/wiki/CodeReviewComments).
There's still a bunch more to clean up, but I figured I'd submit this to make sure you want it before I spend more time.
Most changes are things like returning literals, removing redundant declarations (e.g., `var x int = 0` which could just be `var x int`), and moving variables closer to their use (seemed very C-like to me).

stylistic changes

---

xmlStyle.go

while profiling my application, a reasonable amount of time was spent creating an excel sheet. I did not find any big mistakes or optimization points, but noticed that this trivial inverse map is created often enough to show up in the profiling diagram. I therefore moved it to a static one.

Don't generate map on hot spot in code during iterations, precalculate

---

lib.go
lib_test.go
sheet.go
xmlWorksheet.go

This PR exposes `GetCoordsFromCellIDString` & `GetCellIDStringFromCoords` for public consumption. These are useful functions and have excel related use cases outside the internals of this package.
For example I'm using `GetCellIDStringFromCoords` to calculate the `Pane.TopLeftCell` value.

Expose GetCoordsFromCellIDString & GetCellIDStringFromCoords

---

sheet.go
sheet_test.go
xmlWorksheet.go

According to the standard, this field is a boolean, not an integer (as is currently set).  Without this change correct XLSX files fail on strconv.ParseInt.  
Fixes #275

xlsxCol.CustomWidth should be boolean, not int.

---

cell.go

For my daily work, I have to track events with a precision higher than a second. The current implementation of TimeToExcelTime uses time.Unix, a function that returns explicitly a number of second. 
By using time.UnixNano and changing the divisor, the time stored in the Cell keeps its full precision.

TimeToExcelTime is tuncating time to second

---

row.go

When setting the height of a row equal to another, I have no idea but to use:
`row.SetHeightCM(sheet.Rows[0].Height / 28.3464567)`
So I think a function of setting row's height directly is necessary.

Add function "SetHeight".

---

file.go

Returns error if new sheet name is >= 31 charaters long

Add Sheet length check

---

lib.go

Microsoft OOXML sometimes comes without the floor dimention ref, so we need to fallback to the calculateMaxMinFromWorkSheet
Fixes:
#313

Microsoft OOXML sometimes comes without the floor dimension ref

---

cell.go
cell_test.go
col.go
file.go
file_test.go
format_code.go
lib.go
lib_test.go
sheet.go

cc: @rck109d
With these final changes to cell formatting, the cell formatting is getting really good.
- Boolean and Error cells are now correctly formatted
- The CellTypes now match the actual possibilities from the XLSX spec
- CellTypeFormula was not a real type, formulas can be found in cells of any type (Except for strings which now have their own CellStringFormula type)
- CellTypeGeneral was also not a real type, cells can have a number format string of "general" with any of the cell types.
- CellTypeDate was being used for all dates, even though most dates are stored as Numeric cells with a number format string that has date formatting.
- Cells with formulas that return strings or bools are now round tripped correctly.
- Small floats are now marshaled to XML correctly, previously …

More improvements to cell formatting

---

xmlStyle.go

When reading an Excel file, the property TextRotation is not used.
This request fix it.

fix bug "no read alignment property RotationText"

---

.travis.yml
lib.go

Some spreadsheet software will create files with omitted rows if those rows were empty. The code accounted for ones at the start and the middle, but not at the end of the file.
My code to use this library did not expect that entries in the Row array of a file could be null, and I think that is a reasonable assumption.
I've also removed 'tip' from the go versions that the tests will be run in. For some reason tip takes almost three times as long as the standard go versions, and we wouldn't even change anything if tip started failing. I removed it before, but I think there was a merge conflict with someone else modifying that file that lead to it coming back.

Fixes #147 Prevent making files with null rows on open

---

example_read_test.go

While looking at the documentation for `ReadStruct` I've noticed [a typo in the example](https://godoc.org/github.com/tealeg/xlsx#example-Row-ReadStruct). The code is displaying the struct on error and throw a panic when no error.

Fix documentation showing how to use read struct

---

file.go

When adding a new sheet, the length of "sheetName" is incorrectly determined if there are utf-8 characters

The length of "sheetName" is incorrectly determined utf-8 char

---

file.go
file_test.go

Excel doesn't like certain characters `: \ / ? * [ ]` in the sheet name. This PR adds a check for these characters.
Fixes #407.

Test for invalid characters in sheet name.

---

sheet.go
sheet_test.go

close #388 
Implement a similar sheet.Col method. Get a row by the index of row, if the row does not exist, add row

sheet.row get row by index from sheet issue #388

---

cell.go
cell_test.go

Currently, there's no way to know if a cell stores a time or not, this brings problems if you want to use particular number format functions like `GeneralNumericWithoutScientific` instead of `String` or `FormattedValue`, as times will be smashed to a number.
A possible workaround is to try to parse it with `GetTime`, and see whether or not it returns an error. However, in `parsedNumFmt` is stored a convenient boolean value that can be exposed, without the waste of computational power of the use of `GetTime`.

Add IsTime method to Cell.

---

file_test.go
templates.go

Currently XLSX files created with this library will show a pop up when opened in Apple Numbers asking to replace a missing font. So I'm switching Calibri in the default theme for Arial.  According to this website, Arial is available on both PC and Mac.
https://www.macworld.com/article/1144660/xplatype.html

Remove font warning from Apple Numbers

---

file.go
file_test.go

Adding empty string as sheet name to AddSheet function didn't return any error, but the final file generated is corrupt.

Added validation passing empty string as sheet name.

---

.travis.yml
go.mod
go.sum

Hey people, I'm back!   ..  for a bit at least  
This PR does the following things:
1. Support `go mod` based dependency management (this is only necessary for running `go test` as we don't have any runtime dependencies.
2. Drops pre go1.11 tests from the `.travis.yml` configuration (this keeps things simple).

Port this library to build using Go modules and drop old go versions.

---

sheet.go
xmlWorkbook.go
xmlWorksheet.go

This patch fixes #312 (https://github.com/tealeg/xlsx/issues/312)
by removing an unneeded loop in `xmlWorksheet.getExtent` which,
for large excel sheets, iterates an excessive amount searching for
the desired merge cell via string operations and a for loop.
By adding a map to the `xlsxMergeCells` struct which stores the same
data as the `Cells` the patch preserves backwards compatibility for
any users of the library making use of that struct while also
allowing the `getExtent` function to simply use the cell reference
as a key to locate the appropriate cell.
This does not change the API in any way besides the addition of the
field to the `xlsxMergeCells` struct, so the existing test cases
should cover this.
Signed-off-by: Mark Stenglein <mark@stengle.in>

WIP: MergeCells: Optimization for large sheets.

---

xmlStyle.go

I think reading the Indent was missing along with other Alignment attributes. Added the code, hope this will fix.

Read & Set Indent

---

cell.go

This allows more explicit control of setting numeric types that are not handled well by SetValue such as decimals. Also, all other funcs used by SetValue are exposed already. Adding this now allows a library user to avoid SetValue and handle setting field types themselves if needed.
This could also resolve https://github.com/tealeg/xlsx/pull/422 as this allows the enduser to accomplish the same task without needing to add additional 3rd party dependencies to this library. 
Having this, will allow https://github.com/bwmarrin/sql2xlsx to be modified to convert sql rows into better excel files by handling decimal and other numeric types better.
Thanks @tealeg

Expose setNumeric as SetNumeric

---

lib.go

I had some problems opening excel files in windows, after a while of research on how the library works I found that the switch statement on the ReadZipReaderWithRowLimit was comparing the name of the zip files with an '/' char separating the folders, and i had a '\' in the file.Header.Name

added some strings to compare with \ for better compatibility?

---

format_code.go
format_code_test.go

The `isTimeFormat` function previously didn't account for multibyte unicode characters being valid format string, this code fixes that and adds a test case.

Support multibyte runes in isTimeFormat check.

---

cell.go
diskv.go
diskv_test.go
format_code.go
lib.go
memory_test.go
reftable.go
reftable_test.go
richtext.go
richtext_test.go
sheet.go
sheet_test.go
stream_file.go
xmlSharedStrings.go
xmlSharedStrings_test.go

This pull request add support of the rich text in the cell.
The points are as follows.
`<r>` tags (include children tags like `<rPr>`,`<rFont>`,`<family>`...) in sharedStrings.xml are deserialized to the []RichTextRun.
They can be read from the new field Cell.RichText.
Cell.FormattedValue() returns plain text converted from the rich text.
RefTable can handle both plain text and rich text.
In sharedStrings.xml, []RichTextRun are serialized as `<r>` tags and their children.
To retain white spaces in rich text, `<t xml:space="preserve">` is used to output text fragment which have leading/trailing white spaces.
In addition, conventional normal texts are also processed in the same manner. This may be **a breaking change**.
To add rich text into the cell, Cell.SetRichText() is used instead of …

add support of rich text

---

cell_test.go
xmlWorksheet.go

Don't emit xlsx elements from structs tagged `-`

---

lib.go
lib_test.go

This is on top of the tag `[v3.0.0]`.
This PR makes `ColIndexToLetters()` a bit simpler. The code comes from another repo, which is credited in a comment, and that repo has an MIT license.
(and I agree, xls column names are weird)

simplify ColIndexToLetters()

---

lib.go

[painc_test.xlsx](https://github.com/tealeg/xlsx/files/4699273/painc_test.xlsx)
```go
filePath := "./painc_test.xlsx"
f, err := xlsx3.OpenFile(filePath, xlsx3.RowLimit(100))
if err != nil {
return err
}
```
```
panic: runtime error: index out of range [5] with length 5
goroutine 7 [running]:
github.com/tealeg/xlsx/v3.readRowsFromSheet(0xc00011f0e0, 0xc0000b4080, 0xc00026ed80, 0x2af8, 0x0, 0x0)
/Users/yunzhanghu162/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.0.0/lib.go:627 +0xd11
github.com/tealeg/xlsx/v3.readSheetFromFile(0xc0001d0cf0, 0xc, 0x148cf91, 0x1, 0xc0001d0d10, 0x4, 0x0, 0x0, 0xc0000b4080, 0xc000078ba0, ...)
/Users/yunzhanghu162/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.0.0/lib.go:696 +0x27c
github.com/tealeg/xlsx/v3.readSheetsFromZipFile.func2(0xc0001d0cf0, 0xc, 0x148cf91, 0x1, …
```

fix recover for readSheetFromFile #570

---

cell.go
cell_test.go
row.go

Fixes #586 
You may now use:
`Cell.GetCoordinates()`
`Row.GetCoordinate()`

Rows and Cells can report their coordinates

---

cell.go

Official format for internal links is in form of `#Sheet!A123`.
Maximum number of hyperlinks per sheet is 65530, according to specification.

Fixes internal links

---

diskv.go
lib.go
memory.go
row.go

This PR addresses mutliple issues resulting from the incorrect management of the row.maxCol and Sheet.MaxCol values in both the MemoryCellStore and the DiskVCellStore.

Address issues with the value of row.maxCol and sheet.maxCol

---

file.go
write_test.go

This PR stops the a panic on file write when visiting a sheet where the currentRow isn't set (because it hasn't been visited prior to that). 
Fixes #644

Check currentRow is set on sheet before persisting it (#644)

---

style.go

Excel defines black and white as RGB(0,0,0) and RGB(255,255,255) respectively. 
For RGB_Black and RGB_White to work as expected, we have to switch up their color code.

fix: Switched up black and white color codes

---

xmlWorksheet.go

When no string value is set for a cell, Numbers copies the value from cell A1. Setting an empty string fixes the issue.
This fixes #594. I did see that the release notes for v3.2.1 mentioned this being fixed already, but I'm still seeing the Numbers issue on current master branch.

Fix empty cells in Mac OS Numbers

---

diskv.go
testutil.go

- When testing, files are piling up quickly in the temp directory, now
files are cleaned up after each run (if the test has not failed).
ISSUE: NONE

fix: testing temp files cleanup

---

cell.go
cell_test.go
diskv_test.go
format_code.go
lib.go
memory_test.go
reftable_test.go
richtext_test.go
sheet.go
sheet_test.go
write_test.go

This PR fixes #696 
When the format code handling was rewritten, detecting capital letter forms (i.e. YYYY-MM-DD) was remembered, but substituting them for go date formats was forgotten.  This branch fixes that.

Fix support for capitalised date formats

---

file.go
go.mod
go.sum
lib.go
lib_test.go

Large files can still cause a problem when you want to read all the lines but not all columns. With colLimit now there is a possibility to limit the reading to the set number of columns. Works similiarly to rowLimit, it will only read the amount of columns from the beginning.

colLimit function

---

file.go

Here a risk memory leak without closing file descriptor correctly, when disk write fail.

fix: memory leak risk when file write err

---

data_validation.go

ms office allow max 255 runes in datavalidation input, not 255 bytes.

fix datavalidation dorplist size

---

cell_test.go
format_code.go
lib.go
row.go
stream_cell.go
stream_cell_test.go
stream_file.go
stream_file_builder.go
stream_row.go
stream_row_test.go
stream_style_test.go
stream_test.go
xmlWorksheet.go

Adds support for `Merge()` and `Height()` for `StreamCell`/`StreamRow`.
To merge a StreamCell, call `Merge(h, v)` with the number of extra cells to merge in each direction. Note: does not do any advanced bounds/overlap checking, just ensures that it doesn't go beyond the width of the stream sheet.
To set a custom height, create a `StreamRow` and call `Height()`. It must be written to the sheet with `WriteRowS()`.
This PR also resolves a few tests that were broken on the tip of the v1 branch related to styles and date formatting.

Add support for StreamCell merging and custom row heights

---

.github/workflows/go.yml

Modernize GitHub Actions workflow:
* build with Go 1.20
* drop use of `dep`
* upgrade actions: [`checkout@v3`](https://github.com/actions/checkout), [`setup-go@v4`](https://github.com/actions/setup-go)

Upgrade GitHub CI

---

README.org

README.org:
* update badges
* link to pkg.go.dev instead of godoc.org

README: update badges, link to pkg.go.dev

---

row.go

Add [godoc links](https://go.dev/doc/comment#doclinks) to improve navigation in Row.ForEachCell arguments types.

doc: improve doc for CellVisitorOption

---

lib.go

Close channel when work is done successfully.
A few error cases are remaining where the channel is not properly closed. I don't have time to fix them now, but at least they are now properly marked with "FIXME" markers.

readSheetsFromZipFile: fix channel leak

---

lib_test.go

In my test, RoundTripFileWithNoSheetCols  fails with error `e"OpenFile: open testdocs/after_write.xlsx: no such file or directory"` This is most likely due to the parallel test runs called by csRunO that try to write and remove the files concurrently. [Failed error attached](https://github.com/tealeg/xlsx/files/12566807/failedTest.txt)
By choosing a random filename,
each test create/write and removes its own file,
allowing this test to pass as expected.

use random file name for RoundTripFileWithNoSheetCols test

---

lib.go

It looks like `dump.xml` are merely dumping XML rows that are never read back.
As such it is unnecessary and might cause unexpected errors when the program is called in a read-only directory/FS without serving any purpose.

don't write dump.xml on truncateSheetXMLValueOnly

---

col_test.go
date_test.go
reftable_test.go
richtext_test.go
theme_test.go
xmlContentTypes_test.go
xmlSharedStrings_test.go
xmlWorkbook_test.go
xmlWorksheet_test.go

In my `go test -v`, some tests (like in `date_test.go`) that uses `gopkg.in/check.v1` isn't being performed, even with `check.v` flag.
As such I think it would be better to switch to `quicktest`.  This commit/PR switch all tests coded with `check.v1` to `quicktest` except those in  `fuzzy_test.go`. 
Result of the switch shows that there are more lines of report (which indicates number of tests being performed).
```
> go version
go version go1.21.1 linux/amd64
> go test -v | wc -l
1390
> git checkout switch-check-to-qt 
Switched to branch 'switch-check-to-qt'
Your branch is up to date with 'origin/switch-check-to-qt'.
> go test -v | wc -l
1464
```
Attached are test run results for tests [switched to quicktest](https://github.com/tealeg/xlsx/files/12566911/testSwithedToQt.txt) and  [the …

switch gopkg.in/check.v1 to quicktest in some test files

---

README.org

@tealeg you seem to use `md`, while the README is in `org`
Would you mind if I reformat both `README.org` and `tutorial/tutorial.adoc` to markdown? No change will be made to the content. 
Afterwards I will open another PR.

formatting correction for README.org

---

format_code.go

In [`format_code.go:248-254`](https://github.com/tealeg/xlsx/blob/ac8326d/format_code.go#L248-L254), it was documented that 
> Time formats cannot have multiple groups separated by semicolons, there is only one format.
> Strings are unaffected by the time format.
Apparently Excel 2021 has a *default* numFormat option that violate that condition: `m/d/yy\ h:mm;@`  
It has two formatting sections. Here is a [video](https://github.com/tealeg/xlsx/assets/25011791/79877497-d2a2-46fc-a54a-77af774212be) I recorded in creating this [Excel file](https://github.com/tealeg/xlsx/files/12601286/wb.xlsx).
This commit/PR allows recognition of time format when more than one numFormat section is present, with
- first / positive section having `isTimeFormat` as identifier for `isTimeFormat` for the parsed …

allow recognition of time format in multisection numFormat

---

cell.go

Currently, `cellRef.SetDateWithOptions` will truncate the supplied `time.Time` to **second** accuracy.
This allows fractional/subsecond part to be passed to Excel.

allow-subsecond-settime

---

cell.go

`Cell.SetValue(bool)` sets the cell's value to be a plain string "true"/"false", instead of the expected boolean values, displayed as "TRUE" or "FALSE" on MS Excel.
Add the missing bool type case in SetValue to call `Cell.SetBool`.

Support bool type values on Cell.SetValue()

---

xmlWorksheet.go

Microsoft Excel is unable to open xlsx generated Excel files that contain AutoFilter data. This fix saves the autoFilter XML tag after sheetData and the Excel files work as expected.
Addresses the following issues
- https://github.com/tealeg/xlsx/issues/424
- https://github.com/tealeg/xlsx/issues/727

Fix Excel opening files with AutoFilter data

---

file.go
file_test.go
xmlWorkbook.go

AutoFilter doesn't work in LibreOffice unless a special `FilterDatabase` tag is present in the `DefinedNames` array.  See:
- https://github.com/SheetJS/sheetjs/issues/1165
- https://bugs.documentfoundation.org/show_bug.cgi?id=118592
This pull request adds the workaround that makes AutoFilter work in LibreOffice.

fix AutoFilter not working in LibreOffice

---

col.go
sheet.go

Here's a PR to add a note about column numbers starting at 1 to various relevant functions, which will cause it to show up in the Go documentation.

added more column numbers start at 1 doc

---

tutorial/tutorial.adoc

`GetCoordsFromCellIDString(cellAddr string)  -> `GetCoordsFromCellIDString(cellAddr string) `

docs: fix typo

---

xmlStyle.go
xmlStyle_test.go

Closes #815.
- Indexes of indexed colors should be zero-based.
- Indexed colors used in border styles are missing from output.
Tested with MS Excel and Numbers in macOS. Need more testing with other OS's and spreadsheet software.

fix: wrong cell & border colors using indexedColors

---

sheet.go
sheet_test.go

Fixes #809 
There was a corner case where if you use `sheet.Cell` to open a cell in a row prior to the current row, the current row wasn't written into the cellstore and therefore evaporated if it had never been written.

Fixed issue #809, losing rows from cellstore when moving backwards

---

sheet.go
sheet_test.go

This PR will introduce a bug.
https://github.com/tealeg/xlsx/pull/819/files#diff-736c5868afcf3093a503fb89211daa2dca5ba2b9e2c8fbe5dc105fbbd0e7b963R307
The newly added row index is incorrect, and when reading the data from the row again, it will be empty.

fix: new empty row index bug

---

xmlWorksheet.go

Solving following issue:
I am reading a sheet from an existing xlsx file with ValueOnly() and replacing some spaceholder strings with ForEachRow and ForEachCell with SkipEmptyRows and SkipEmptyCells as parameters. Saving the results Save() serializes the xlsx file into file, with empty cells covering my celloverflowing replacements.
The actual code skips only empty rows. This pull request adds the SkipEmptyCells to ForEachCell during serialization and avoids unnecessary cells.

fix: Empty cells covering overflowing text of left cell

---

file.go
lib.go
lib_test.go
reftable.go
reftable_test.go

This PR save a few megabytes on the shared string table decoding.

Use sync pools for shared string parser

---

cell.go
diskv.go
diskv_test.go
file_test.go
sheet.go
sheet_test.go
xmlWorksheet.go

The elements inside a worksheet are defined as a sequence, meaning excel expects the elements in a specific order.
Hyperlinks currently are written before sheetData, but must come after sheetData, otherwise it will fail to read them.
Also internal links need to be stored in `location`, which currently get's lost during save.
This fixes #836. Also it adds support for handling internal links in Excel-readable way.

Fix hyperlinks in excel

---

cell.go
write.go

When setting the value of a cell to an unsigned int, it can be handled identically to signed ints.

Handle unsigned ints

---

file.go
file_test.go
utility.go
xmlWorkbook.go
xmlWorkbook_test.go

Sorry for creating as new PR, but it's still relevant. I can't reopen the closed pr.
Defined names can apply globally (i.e. for every sheet in the document). Global defined names have no LocalSheetID attached to them. LocalSheetID=0 means that the defined name only applies to the first sheet. By changing the type to `*int` the information will be preserved correctly.

Change LocalSheetID to pointer of int

---

file_test.go
lib.go
xlsxRelation.go
xmlWorksheet.go

Currently, when a file is parsed, existing relations are not parsed and therefore get lost.
This change ensures existing relations will be kept correctly. Fixes a nil-dereference, when trying to open and immediately save/marshal a file, which contains hyperlinks.
Should fix #842.

Read relations when parsing a file

---

row.go

If a sheet were renamed and then new rows were added, the new rows would not be saved in the .xlsx-file.
To fix that, makeCellKeyRowPrefix() and makeCellKey() were updated to use cellStoreName, so they use the same key-prefix as makeRowKey does.
Should fix #845

Fixes issue when newly added rows are missing from file
