- lib.go
> Sheet.File is not assigned when creating object

- cell.go
- write.go
- write_test.go
Basically what we talked about in https://github.com/tealeg/xlsx/pull/83 just with an added function for writing slices.
> added int64(), setint64(), and (*Row)WriteSlice() functions

- lib.go
- lib_test.go
- sheet.go
- xmlWorksheet.go
I've gotten this far enough to thread the data through I care about successfully, but wanted to get your feedback on a couple of things.
1. How much of the sheet view do you want implemented before exposing it? Right now it just has the Pane object
2. Should SheetView and Pane be in their own files? They don't have any methods on them so it seemed like overkill but it's consistent with what you've done to other publicly exposed structs like Row
3. I tacked onto an existing test case. Should it be in a separate test case?
Thanks in advance
> Add basic support for reading freeze and split state out of worksheets.

- lib.go
- lib_test.go
- sheet.go
- xmlWorksheet.go
These can be created by dragging a formula across a set of cells.
> Support for shared formulas

- file.go
- hsl.go
- lib.go
- sheet_test.go
- theme.go
- theme_test.go
- xmlStyle.go
- xmlStyle_test.go
- xmlTheme.go
Right now this is only used to color cells that use theme colors
> Initial support for themes

- style.go
- style_test.go
- xmlStyle.go
- xmlStyle_test.go
Some initial support for B/I/U when reading XLSX was already there, I went ahead and added writing support as well.
> Added bold/italic/underline style support for writing.

- cell.go
- cell_test.go
> Added date format yyyy/mm/dd

- style.go
- style_test.go
> Fixes typo of Default (missing "t") in style stuff.

- lib.go
> prevent un handled panic in open xslx

- file.go
reading xlsx file from raw bytes(useful for web server)
> add OpenBinary & OpenReaderAt

- README.org
receive a second return value
ref: https://godoc.org/github.com/tealeg/xlsx#File.AddSheet
> Fix sample code on README

- write.go
- write_test.go
[fmt.Stringer](https://golang.org/pkg/fmt/#Stringer) support for struct fields in WriteStruct and for slice values in WriteSlice
> fmt.Stringer interface support in WriteSlice & WriteStruct

- sheet.go
> fix not writing to file for some items in Alignment style.

- xmlStyle.go
> alignment attributes can be missing but they can't be empty

- file.go
- lib.go
- xmlWorkbook.go
- xmlWorkbook_test.go
added DefinedNames to the file struct by looping over defined names in the function readSheetsFromZipFile(), tests pass,
updated the DefinedName struct from the MS docs
> added support to read DefinedNames

- README.org
Added familar godoc.org badge to top of the Readme
> Added familar godoc.org badge

- README.org
From what I can gather, this is a typo that I fixed.
> Fix the project name in the readme header

- lib.go
- lib_test.go
Populate the row height and custom fields.
@tealeg Please review.  Thanks!
> Populate row height and custom fields

- sheet.go
- xmlWorksheet.go
Hi,
I've fix issue  #179 to support frozen pane.
Thanks for your lib, very useful.
Signed-off-by: Francis Bouvier <francis.bouvier@gmail.com>
> Fix SheetView Pane

- lib.go
- sheet.go
This should fix issue #248 (merging cells produces empty style attrib). Also includes some cell bounds checks by user K1000000.
> Fix for issue #248

- xmlStyle.go
I hope, I have placed changes in proper place.
> fixes issue #251

- cell.go
- cell_test.go
Sorry. I mistake. Cell.GetDate()
> Add method Cell.GetDate

- sheet.go
- sheet_test.go
- xmlWorksheet.go
- xmlWorksheet_test.go
This PR adds basic support for defining a filter area.
> Add basic support for filters

- cell.go
- file.go
- file_test.go
In cases where Sheet(s) is created before File
> Func. appending an existing sheet to a file

- lib.go
This was done by moving the channel close to the writer goroutine (as is idiomatic). readSheetFromFile
now returns an error to stop the writer routine from trying to read more
sheets if one contains an error (this will prevent goroutines from
leaking due to readers that stop reading on receiving an error).
This might fix issue #278.
> Fixed the datarace surrounding the channel. 

- cell.go
- cell_test.go
- file.go
- sheet.go
- xmlStyle.go
> Treat hours correctly

- README.org
https://github.com/tealeg/xlsx/blob/2ee7bde0c2f1ddf862bd3ac7f3ac95df15ca7aa7/cell.go#L90
> docs: fix cell.String only return one value

- file.go
Added the sheet name length check to function description.
> Improved file.AddSheet documentation

- write.go
- write_test.go
> added handling of 'database/sql' module NULL datatypes

- col.go
- data_validation_test.go
- lib.go
- sheet.go
- xmlWorksheet.go
> Remove off by one error

- cell.go
- cell_test.go
- col.go
- stream_file.go
- stream_test.go
I could not figure out how to procure a `StreamStyle` from `AddSheet` on `StreamFile`. So no `StreamStyle`s are being honored by this method. SImply `StreamStyle{}` for each `StreamCell` is passed down to `writeS`
> 'WriteWithDefaultCellType' writes all cells in a column as the default cell type of that column

- .travis.yml
- fuzz.go
- fuzzit.sh
What would you guys think about integrating with a fuzzing platform? [Fuzzit](https://fuzzit.dev/) is giving free service for open source.
They run [go-fuzz](https://github.com/dvyukov/go-fuzz). It's one of these genetic fuzzers. It instruments your binary and detects branches, then uses that to decide what to mutate and what to keep the same. It tries to evolve knowledge about your program and eventually walk all the branches.
This patch fuzzes parsing and cell stringify to get some round trip coverage.
Build will fail due to missing an API key. If you're interested setup is like this:
* In Fuzzit create target `xlsx`.
* In Fuzzit settings grab an API key. In repo settings in [Travis](https://travis-ci.org/) paste it to envvar `FUZZIT_API_KEY`.
Possibly contributes to #127.
> Continuous fuzzing

- col.go
- stream_file.go
- stream_file_builder.go
- stream_style_test.go
- stream_test.go
- xmlStyle.go
I was added support custom number formats for StreamFileBuilder and merging cells.
> Merge cells for stream file and support custom number format

- sheet.go
- sheet_test.go
> Write the style for a column, even when no numfmt is set

- cell_test.go
- diskv.go
- style.go
- style_test.go
- xmlStyle.go
- xmlStyle_test.go
> Font sz should be a float

- lib.go
- lib_test.go
> Be more tolerant of novel file layout in xlsx files

- style.go
- style_test.go
- xmlStyle.go
- xmlStyle_test.go
Added support to read and write "Strike Through" font style property.
> Add support for read/write strike style

- xmlWorksheet.go
Microsoft Excel will fail to parse a worksheet with a mergeCells element that occurs before the sheetData element.
Excel reports the error `Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Load error. Line 2, column 757.` when attempting to open & repair a workbook generated with the following code:
```go
func main() {
xls := xlsx.NewFile()
sht, _ := xls.AddSheet("sheet1")
row := sht.AddRow()
cell := row.AddCell()
cell.Value = "test"
cell.Merge(1, 0)
path := "merged-broken.xlsx"
xls.Save(path)
}
```
> Emit mergeCells after sheetData for Excel

- xmlWorksheet.go
-  adjust the order of data valiation xml node to avoid prompting errors when opening excel
close #610
> fix: ues data validation, open file tips has question issue #610

- file.go
- file_test.go
- remove a sheet from file #590
- rename a sheet from file  #602
close #590 #602
> Feature issue remove rename sheet

- stream_file_builder.go
- follow https://github.com/tealeg/xlsx/issues/365#issuecomment-431719853 to fix open xlsx need recover issue
> fix: Need to recover xlsx which created by NewStreamFileBuilder method #36

- sheet.go
> Give a more meaningful panic when trying to use a closed sheet

- sheet.go
> Check that relations and relationship exist before accessing. 

- xmlWorksheet.go
fix :
ues data validation, open file tips has question 
close #679
> fix: Can not open excel files when added data validation #679

- diskv.go
https://github.com/tealeg/xlsx/issues/677
> Misspell: require

- xmlStyle.go
> Fix: issue #705: index out of range on xlsxIndexedColors

- README.org
This PR fixes a typo and improves some word ordering.
> Improve wording in the README.

- file.go
I've added a function to allow the library user to add names to the worksheet. At the moment names are read-only.
> Allow to add names to the workbook

- lib.go
issue here https://github.com/tealeg/xlsx/issues/739
> fix cell regex expression match f tag in a cell

- file.go
- lib.go
* Fix leaks in lib.go reported by @zhangyue9999 in #747
* Fix leak in OpenFile
> Fix read zip leaks

- cell.go
- cellstore.go
- col.go
- file.go
- format_code.go
- fuzz.go
- fuzzy_test.go
- read.go
- sheet.go
- xmlStyle.go
- xmlStyle_test.go
Apply gofmt: `gofmt -l -s -w *.go`
This cleanup will help the work of contributors.
> gofmt with Go 1.20

- lib.go
`errors.New(fmt.Sprintf(...))` -> `fmt.Errorf(...)`
> Fix errors.New(fmt.Sprintf(...))

- go.mod
- go.sum
Upgrade quicktest which has fixes that I submitted myself. See https://github.com/frankban/quicktest/pulls?q=is%3Apr+is%3Aclosed+author%3Adolmen
> deps: upgrade quicktest to v1.14.6

- file.go
- file_test.go
- sheet.go
> stable cellStoreName in they key for the cellstore

- xmlStyle.go
> fix: addNumfmt
